### ISSUE TITLE
fix API usage scheduled for removal (complained by plugin store)

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-common#93]
![image](https://user-images.githubusercontent.com/25126/128572913-8846e76a-2c34-4e59-9416-a98a10595734.png)
![image](https://user-images.githubusercontent.com/25126/128573036-619c45a0-fcef-48ea-8265-efdfaaa9ea3c.png)
![image](https://user-images.githubusercontent.com/25126/128606245-1b8f3e3f-224a-4a0a-b170-e26221c11b72.png)
![image](https://user-images.githubusercontent.com/25126/128856273-8e2d4d7d-0a08-4a63-8301-d97344823ad1.png)

**Comment by adietish** [comment]
@jeffmaury, @lstocchi: `ExecHelper.createTerminalRunner` has a problem without an evident solution.
It is creating an anonymous subclass of `AbstractTerminalRunner`. `AbstractTerminalRunner` has a breaking API change in `2021.1.3`: 
* < `2021.1.3`:
`protected abstract T createProcess(String process)`
* >= `2021.1.3`
`      public Process createProcess(@NotNull TerminalProcessOptions options, @Nullable JBTerminalWidget widget)`

`TerminalProcessOptions` doesn't exist < 2021.1.3

Thoughts?

**Comment by lstocchi** [comment]
I guess we can do what it was done before for 2018_3

https://github.com/redhat-developer/intellij-common/blob/3e2398854237612ee63482b354485448d6f570e4/src/main/java/com/redhat/devtools/intellij/common/utils/ExecHelper.java#L433

That line can be removed. It is always true because we only support from 2019.3. 
We can add a check and create the `AbstractTerminalRunner` based on the version used. If this is the only thing that changes

**Comment by adietish** [comment]
> That line can be removed. It is always true because we only support from 2019.3.
> We can add a check and create the `AbstractTerminalRunner` based on the version used. If this is the only thing that changes
But the problem is afaics that there's no class that we can compile that's binary compatible on all platforms.
`LocalTerminalDirectRunner` still exists with an unchanged API on **2021.3** but then it requires us to create a `PtyProcess`.

**Comment by lstocchi** [comment]
Yes this is somehow what i was thinking, I remembered there were other impls (one is the one you mentioned `local runner`) and i thought to use them for >= 2021.3 and leave the code as it is for previous version but i didn't remember it was creating a PtyProcess :tired_face: 
 
In https://github.com/redhat-developer/intellij-common/pull/91/files i am using `createLocalShellWidget` to overcome a problem i had in knative, i was waiting Jeff to verify it on Windows. If that works we could think of use that one as well. The problem is that in old IJ version the terminal tab will be opened with `Local` as name. In newest IJ versions (>2020.3 :thinking: ) they allow to define a custom name.

**Comment by adietish** [comment]
@lstocchi replace `AbstractTerminalRunner` by `LocalTerminalDirectRunner` since the latter is unchanged across the IC versions. This required `Process` to be replaced by `PtyProcess`. Please have a look if this looks ok to you or if your solution (used in knative) is superior.
